version: '3.8'

services:
  diffusion-for-shared-autonomy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: "1002"
        GROUP_ID: "1002"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - DIFFUSHA_DIR=${DIFFUSHA_DIR}
      - NAS_DIR=${NAS_DIR}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1 # remove?
      - LIBGL_ALWAYS_INDIRECT=1 # remove?
    volumes:
      - ${DIFFUSHA_DIR}:/code
      - ${NAS_DIR}/data-dir:/data
      - ${NAS_DIR}/output-dir:/outdir
    working_dir: /code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ 'all' ]
    stdin_open: true
    tty: true
    command: /bin/bash
