version: '3.8'

services:
  diffusion-for-shared-autonomy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    volumes:
      - ${REMOTE_WORKSPACE}:/code
      - ${REMOTE_WORKSPACE}/data-dir:/data
      - ${REMOTE_WORKSPACE}/output-dir:/outdir
    working_dir: /code
    runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           device_ids: ['all']
    #           # count: 2
    stdin_open: true
    tty: true
    # command: /bin/bash
    command: /bin/bash -c "while true; do sleep 1000; done"


