version: '3.8'

services:
  diffusion-for-shared-autonomy:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1002:1002 # FIXME: replace with your user/group id
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - REMOTE_WORKSPACE=${REMOTE_WORKSPACE}
    volumes:
      - ${REMOTE_WORKSPACE}:/code
      - ${REMOTE_WORKSPACE}/data-dir:/data
      - ${REMOTE_WORKSPACE}/output-dir:/outdir
    working_dir: /code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ 'all' ]
    stdin_open: true
    tty: true
    command: /bin/bash
